import type { AppProps } from "next/app"
import Head from "next/head"
import { AuthProvider } from "src/utils/useAuth"
import "src/styles/globals.css"
import "bootstrap-icons/font/bootstrap-icons.css"

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>KanBox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AuthProvider>
        <Component {...pageProps} />
      </AuthProvider>
    </>
  )
}

export default MyApp
